language: node_js
sudo: required
node_js:
  - '4.3'
  - '7.2'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
after_script:
  - npm run remove-coverage
env:
  global:
    - 'MAJOR_VERSIONS=master,stage'
    - DEEP_NO_INTERACTION=1
    - E2E_TESTING=none
    - secure: 
        Z3aXClHMpz/bp9KtM+XYJI6jI6IqeBhV5tIbAx2EHVF5AkjD23z158RyyYfvE26SHUFb9TLMs/kjkcEe/vH0nXKSmsA4vqtGuZWqky8WWy9hKh3S38eKtWjnipjTIzgzgCE5bJ1woA4UeZfSsMHP8T9ncCbDQ1jOGQNUD46fQmJxlwz5dO9uQech9lMQlbE3kyCv6ZCdo0jx3cqZaP4YH3NWLwrMqHYkvg5Kg2olUXalUDj8sYvv++7YUns2llmi8dlMGM2phQjyygUsQWEBy5FgVmn+ruHlx5bgs0BCNVNpGM7zmCi8B+5LQyNQ7T66Ifqi+nigt0yNbKlRZ66dvoJa2BNltTAtiThD3aTYG7MRiFr5iJgoZ6C8tzVnQdB+lDkuRg0DhhldFU4O5bl34iGgOVhHsTkWZIgHGCC1nNdqw7LXcuYxo9ei3iIvVTJMEGdpgsrOiX6d6Y4f1IuoyH/x5DPAVeGO26UMVHpWDMJRvaFcCjREAlJHgNSZCv+0td3iUzO/V9piHouVBjvhj8UonhSnTJG3ms1Qlpt7S+Gu2nI0fPCWrsA8UnkGBT8ugQAer8n4Tjgd4AK0+zE7fFLDHxxTTQm+xn5AuTR0eoIxSOZ+lb4dfZGEVrGf6wyFqocMwHd9qIehnovRVM+mPKignxh9hs+3Y/oojngMLgc=
    - secure: 
        OtGYtdtHf7IQq9Lp5pP81wAp5pwBjpsogfgIipQmw3Loxs49dyXOL8j3Wzo0yon0WYwygsnDziSm2X+QYls1Od5KUxDazuHk5/9M2pazphNU7AWSPVHOXFQ1wGZa/r04+lS9lJlgvlQ3MibUobHZ7705QxFzmyKsSJe+L7bioMOSlEYiarACifuewu3PJxHadUoIPDVOjDv4zYMlritnqYPrXSFi37mLz3HSTmzeQiw9EVSkV10DtIK2KurAcTEGtL263vxTLxv/rRMnjGqlnEwyJl3nB3njiiQkGfIJDDUDuwCPMF3lyKkK0iAoDXmAb6fPbFhcJhasEHPmfTol42fj1wwOLBfL68ko3Qh+Ux2d9Y3dx2Iu+q0NVdl6UNFAiSZbjJYBhdqmmqCtYY4bZ5s5gy0RKGIiOZHc7JxTWeUT2UtZEI2wYZyv9qZ3v/FomjuVcRoQ3QxGJOqT1Zc0fowYQV89bnwRIo04mhEDn+riZjOxmhfeSB8w8/awS+aitljD8CphNDt8187W+Y8qeP2I46Xj88GseEGuFSAC9g+C0B9WJxuGSM6NV3QY3R74b0xINfoCv6ECSakXJzbH8Phd8Tc0kdDxvoOSUS2Py5L1bNcRubpv2TApPnjGUh4SNRerSVAnHPUJVffDdkPzXoYl6X08UFifSNK2V5DEznc=
    - secure: 
        RDfBefcxmTmrTTSpZiF7eq2bzeMicWXCkh99xQUID5m9j9vCoKdc/+9rNAy2qE7mmapNm2tVME54yv2DcwQlsQYie2vyRVjILbFojVfiZk3qDEmflfe+h00lt4ONHABmhu6yPVtZdoVtCmT9NndCrDCl0j9eNKTaFqjHTB26uegOvnwTdTwdz9qIyY0YglzzVhshvDV2uLbWekRKwT29lbBvllLsD4RgD54IVcoP15hYB5vCsN1p3hFVv+OHkdA4rmoaxGTwVVW9DYz+TdwwQvFdRbJSLlqe7Zw3Vj93pGzO0Wf1GMya6m9ZJZ6epqVVOCY6yuXPqVc5CSKoj42yc/mdrF4KZDrFQBWO2Ou3w93lJR6GVuCJAL0agEXtCSIoDvyQe3LBodZ7OTUp6d62RNzpXJh89Ll47kjJW8NWP4QBCyyC48Q86Mkc1ZPOKv1xEj5a8PmC6APuFnZbph8fOBIe/wnHFEmAC2DVS1wqiIRTzmCxLQ7SSNGV7cBQI5DGn18YMBijMaOm+VFJDVV18ggTFikad1ihdilyI3AU/JjSMWiv179MjPot+h13sbrazCLnvDqu3Dfm7gebQ9Y0b8b4O+/jRklNrUp3+OP5fFGJTewk2CnhtZdsbZ0c3F5c3CZykWAonRJ9/5MzXwvj7ZSbvlYtcRwf3umrKkNPu1M=
    - secure: 
        rHUtraRIX/mYLHFexum7wepfl4tyjmQgWA/eFSC27FQd4JR3aZBf14m3M+8u06VLSaCwNJtPsc4bTSNeukWcrVhFzWogaDMVknbDWa3OjxzCdSCP1eyKq7V6q1W+5KqkL4b5m+2WvrUaRQ9PnJTzhAhX+XUHOAmHqMcq6MRKsCU1iZq6usb/TJU5dO/hO/ouQgOevh000GCpqrwjp9CXUedaMPpopLdioQVm7p0mias7UQ8rvtvvypNm6+oO6lAZIntFhCtQ8e4vaHJ1ODDJEzQBZm1A9b/Sh3vEAIi0YEFP3rRUAqKuSRvdX+cqvgJGm7Ws/frzvLxnKd6voGAFtvOZ8x0LgIyMPvFyqqyp1eA73G0F5ZPVWe9KhCIxfi/rx9enThheVSuU5SydLAVfe7VpkhEOGoTPkPDYV06BLYd/7QRQ5emt9j6zd/6hh389i2EFbwxu0GTgcLo6mVnksgldgRtKhqDNUzB9tem2Y++cKyiY4dYx6HT9n0NELNtc7RH9d+UzmzzO16PvUil4Kwm13wqjAv0J56l0YVPC9F8S0Xf7DmJxqbbLZ/AZoKejTNpuyKkN68t0pTQqXoQ8PuQOjPtTP1HS9ei18Hc5pF8wAOFM2GLyDn41/BVAQv30uRSgvf2vqtRNvCvTf6cGNJZClBegi3DO318dwg2KlEQ=
    - secure: 
        eHdUpa05KjwcQ6G1TM6X2dT6PvX+tj6tBLynkxip+37DxF1C1UYI858kK5phSz6IxzQpzOymnQK3AcMkXbzfJ6Rcqu2YG0xb558VyOUa5GUElEgTMNK7lcQFxYYQXkSCA296AdoVhb3mGl9PLCUQSVfILaDcO/gvhZZXaLnqkKf10INTQx4s6pg1RL73TnBLl1R01idTY2zzlG4bDIfep94REf9ZlFQYUjzWbuRsQyXGNW7efvVCd/o12Th8AF5L9rexaG7Nz28a3OP7GKoMotFNbtXiciX2GldjmXJQ+HlTUlxPGq3r7KK+4NMY5UUs9I57QmvnNNEVZ8QiEC4Qt5CyMwepb2DKiBPmA4YzhlvwhDSpSLVkNC1+IajiTbEp4+zDYG5F1GjpDOgOVWclK8MZ9qAhCY1NQORiezw/uwxWzdV0fBIrwaefxfkv/43/TWLWzNf6uFkDiSSNhiP4ZkVitc80PRW8/PqCbc3viiIIfn1zJ6WFgsfJeSFUf60K8JUV/K9iOrgXKX/mkqWV7c216+cnqlJwaCJ7HwrS0BUzmecNs+1+sOlsX3wMaat0Cq+PNzPSaT2B4cSKG4g9+m6Cr7/0GjkJ/PSPnJd227XkxhqtE9/FQVySxmkzm5EwH3q9yUwFvA+aynB+MjAZ2biG/W9iv2NONVLUVCVq5ZA=
    - secure: 
        VHUlW4gdhQXbnMpuVXP9/y3NqohbACrbjG/wd23rAbsKHuCR/1IJRcVGr74+pgc/M1UUKH9GOc8divTuRiCD8Oz+BrLdGBs46iYlcAeIlrmvkyxdLIqdZvsStd+FV55g/TjqFwS9cRtoZ9OQ35sxrtQ9YV+sYiBj3hv8A/jtGfcA9qXOwI1NFsZWuAcXtlrseDWmT6TgsA89NyU9SnWr3rbAhL4lvzUe2n0TcfEJV3uIRXQjXEKoOk/kBjmIHqmdRfE045zX4N2N9ADvwcuRq4xUU2NBLDIj+gmfn1C+JZFog4dfb+RAvYUuWy/OgK9ThYTMtdqDgs0Tlh3JKjuVlM0p6ng/7P2OBuLuSJO+fO+hTuRgbIrLL6PemVGyrOpXzaXOO8h/gRcf1uBPW3LqLCvh0tt5P30rBxwOqrraAOunKhipXxRlTv3WiiOF+HE/TNuTQvooJk6M92Oed+ysOpn6KIcRhQwVSWUjZtAZ8yIN4EX4nqkOSN7Jb6Uoxn5AnYilJZrmKMTniS936zI93ASEoMVyO8+L92iKFWHtZUi4zI6y3vi/dm+SCQJNnBeLouEc/FfQ9FslrV/Z245XOtDVB713zcNuJ2gnoeVAVKIeUtleFqg5O3tXFkexL53dZvpOfm68TIgeBvFi/qWUiV+NwzArfEKv7D0QEFLmb3c=
    - secure: 
        Rn7fL3r+OMWRJ6WG0bfCgIL7vdoX//14dVu6rbaNlnzKjs6gO+9pXgo2kgBN+xgvA5EytRQ8bOcY8BLopyeHHY4BT/2t23ObCBOYKWrWf3Sm/ds4vFfXieDgpuEHMTyVJ8YjWZIYnPGyOxAUR7bWen1+6rCpQ/Qw1wRKgM3tsokjg9PjOcu8acrzkIo+xDzUb9hgG9GGmNBgzrkbxM090Exz8HPHP4TAjIl3lT/UpVQvAdu8MFn7fULuSLGMoCCp6RXwtKAvncrjtw3oLpMR5vz7pBwcBDHNE1pZ6Ovx1ijH/Rpu3ISmiF2BEUqtMgdIpou8ILe/dpyeHi49N2YqCqxM00EsFb/IuWqtY3PptgjtcRxVfl8+987KFcD+J2lLSeNlx3CSd1DOYo+hSMdMaQhiPYLniRrHGGFrXA/QRLsP6AzvMSDTlXtmbVc0HCoabfLGNT2nLTtd2uK+0OEKzcs/viLhli2D6b1KUjA9d1PKTc2ukyiRBjILhFHYXCXA3drkcskIdGakfGsZFzCQXWpJ87y8GPmJP/dPARay6UIHIdwDrEBFQ2VzvoBXOIdtjvn6papeq5fpyBywEEbRnzIoE4rAWoYABejHF2khGHinu+vCRK3cfT4JrERtY4DvqNd0fxskCIkpN6hm24D5dbAbsb8f8kxtOfvLwsm/r1E=
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
notifications:
  slack:
    - secure: 
        FY4j5LSTnOd/eIYXb3e2J6FksaWw+6VYr9yeV8D8wzAxV+IPqP//hNLbiGJmoNQlewgMVyyW99Ebzf3jVn1zNkEjVFKys1fV7qM4l83Hf5fDFEzaLvJxl23arg1oJ3OFEqTrebbR6t709xd9/O61sE3gcIrT4QlRI62a2aA5SoNsqBqx1rFN9hAZInHvjePdk37Z9Zxrb44f/3SbyNpidQIlN3Jb9n0caJPE8lA0k/++/YyDPTDrI9AXRthgT0WUc6rV65MaA3F1NgS51/2XfLvImjLt4pVW8h89RYJS7V3CtasL3OU9YtcvrMNcprrnVDHUFyurUja5f7lfO8mfPfjBoIeDIk90Kn7KMzGkbbYh6j4kq9/ZecRCVuZWwaibgspYuMUEXvYE2MBshvR4EducPmmN3O+Pr1wTNZl5pxU1L7yuSrH/5JBWrpIXDCXkYn0apU3IG6Cc5nOSTQDDz9OhALrAoj6PWIM72uBIKmURsnOm9fcu6lH1Xd+NelXGypFULYfZmwUHdpWEcecqYyTLygHw8Z0qNusC4nkX5dFPReAyv2Ea5G0yzYUcLnCgsn/0AM2ePFpZrMD1KP8QfoPyIQQ9PLltjx/Ga2HEBSOQxeyiv+sMPEmaorc9T3hDhPqxCyl11WGGfFWZ8NQMnyEDnZkwaPz4mi8VPwWZvDQ=
addons:
  sauce_connect: true
